// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220920171029_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("GroupID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fakultet")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Kurator")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Starosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = "101",
                            Fakultet = "ФДП",
                            Kurator = "Хохлова Наталья Николавена ",
                            Starosta = "Гузнова Анастасия"
                        },
                        new
                        {
                            Id = "201",
                            Fakultet = "ФДП",
                            Kurator = "Бородулин Никита Дмитриевич",
                            Starosta = "Шашкин Сергей Дмитриевич"
                        },
                        new
                        {
                            Id = "301",
                            Fakultet = "ФДП",
                            Kurator = "Шумкин Александр Николаевич",
                            Starosta = "Юров Данила Алексеевич"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("GroupID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "101_1",
                            FamilyName = "Фиксина",
                            GroupID = "101",
                            Name = "Кристина"
                        },
                        new
                        {
                            Id = "101_2",
                            FamilyName = "Котова",
                            GroupID = "101",
                            Name = "Евгения"
                        },
                        new
                        {
                            Id = "201_1",
                            FamilyName = "Кто-тов",
                            GroupID = "201",
                            Name = "Кто-то"
                        },
                        new
                        {
                            Id = "201_2",
                            FamilyName = "Зузин",
                            GroupID = "201",
                            Name = "Михаил"
                        },
                        new
                        {
                            Id = "301_1",
                            FamilyName = "Крюкин",
                            GroupID = "301",
                            Name = "Евгений"
                        },
                        new
                        {
                            Id = "301_2",
                            FamilyName = "Данилов",
                            GroupID = "301",
                            Name = "Алексей"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("GroupID");
                });
#pragma warning restore 612, 618
        }
    }
}
